import { Trip, Flight, Accommodation, Budget } from './types'

export const SAMPLE_FLIGHTS: Flight[] = [
  {
    id: 'sf-1',
    direction: 'outbound',
    airline: '이스타항공',
    flightNumber: 'ZE613',
    departureAirport: '인천 (ICN)',
    departureDate: '2026-02-06',
    departureTime: '15:05',
    arrivalAirport: '간사이 (KIX)',
    arrivalDate: '2026-02-06',
    arrivalTime: '17:00',
    bookingRef: 'U53W5C',
    priceKRW: 115000,
  },
  {
    id: 'sf-2',
    direction: 'inbound',
    airline: '이스타항공',
    flightNumber: 'ZE612',
    departureAirport: '간사이 (KIX)',
    departureDate: '2026-02-09',
    departureTime: '11:50',
    arrivalAirport: '인천 (ICN)',
    arrivalDate: '2026-02-09',
    arrivalTime: '13:50',
    bookingRef: 'U53W5C',
    priceKRW: 134600,
  },
]

export const SAMPLE_ACCOMMODATIONS: Accommodation[] = [
  {
    id: 'sa-1',
    name: '사라사호텔 신사이바시',
    address: '일본 오사카 Chuo-ku',
    checkInDate: '2026-02-06',
    checkInTime: '15:00',
    checkOutDate: '2026-02-09',
    checkOutTime: '10:00',
    bookingPlatform: '아고다',
    bookingRef: '1687417333',
    phone: '+81 6-6241-3391',
    priceKRW: 188189,
  },
]

export const SAMPLE_BUDGET: Budget = {
  localCurrency: 'JPY',
  exchangeRate: 9.5,
  items: [
    { id: 'sb-1', category: 'flight', label: '항공권 (왕복)', plannedKRW: 250000 },
    { id: 'sb-2', category: 'hotel', label: '숙박 (3박)', plannedKRW: 200000 },
    { id: 'sb-3', category: 'food', label: '식비', plannedKRW: 150000 },
    { id: 'sb-4', category: 'transport', label: '현지 교통', plannedKRW: 50000 },
    { id: 'sb-5', category: 'activity', label: '관광/입장료', plannedKRW: 80000 },
    { id: 'sb-6', category: 'shopping', label: '쇼핑', plannedKRW: 100000 },
    { id: 'sb-7', category: 'etc', label: '기타', plannedKRW: 30000 },
  ],
}

export const SAMPLE_TRIP: Trip = {
  id: 'sample-osaka-kyoto-2026',
  title: '오사카 · 교토 여행',
  destination: '일본 오사카 · 교토',
  startDate: '2026-02-06',
  endDate: '2026-02-09',
  isInternational: true,
  flights: SAMPLE_FLIGHTS,
  accommodations: SAMPLE_ACCOMMODATIONS,
  budget: SAMPLE_BUDGET,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
  days: [
    // ──────────────────────────────────────────
    // Day 1 · 2026-02-06 · 이동 & 오사카 첫날
    // ──────────────────────────────────────────
    {
      date: '2026-02-06',
      items: [
        {
          id: 's1-1',
          type: 'transport',
          title: '인천공항으로 이동',
          time: '10:00',
          duration: 60,
          location: { name: '인천국제공항 제1여객터미널', lat: 37.4491, lng: 126.4503 },
          notes: '제1여객터미널 출발',
        },
        {
          id: 's1-2',
          type: 'transport',
          title: '인천 → 간사이 (ZE613)',
          time: '15:05',
          duration: 115,
          location: { name: '인천국제공항', lat: 37.4491, lng: 126.4503 },
          notes: '이스타항공 ZE613 · 예약번호 U53W5C',
        },
        {
          id: 's1-3',
          type: 'transport',
          title: '간사이공항 → 호텔 이동',
          time: '17:00',
          duration: 59,
          location: { name: '간사이국제공항', lat: 34.4272, lng: 135.2440 },
          notes: '난카이선 → 신사이바시역 → 도보 7분',
          price: 1170,
          currency: 'JPY',
        },
        {
          id: 's1-4',
          type: 'hotel',
          title: '사라사호텔 신사이바시 체크인',
          time: '18:00',
          duration: 15,
          location: { name: '사라사호텔 신사이바시', lat: 34.6742, lng: 135.5002 },
          notes: '예약번호 1687417333 · ☎ +81 6-6241-3391',
        },
        {
          id: 's1-5',
          type: 'restaurant',
          title: '저녁 — 스시 오마카세',
          time: '19:00',
          duration: 60,
          location: { name: '타치스시 마구로 잇테츠 센니치마에점', lat: 34.6687, lng: 135.5009 },
          notes: '난바역 근처 · 예약 필수',
          price: 5000,
          currency: 'JPY',
        },
        {
          id: 's1-6',
          type: 'activity',
          title: 'DiCE 오사카 — 오버워치 콜라보 카페',
          time: '20:30',
          duration: 60,
          location: { name: 'DiCE 오사카 도톤보리점', lat: 34.6689, lng: 135.5011 },
          price: 2000,
          currency: 'JPY',
        },
        {
          id: 's1-7',
          type: 'attraction',
          title: '도톤보리 야경 산책',
          time: '21:30',
          duration: 30,
          location: { name: '도톤보리', lat: 34.6687, lng: 135.5009 },
        },
      ],
    },
    // ──────────────────────────────────────────
    // Day 2 · 2026-02-07 · 교토 당일치기
    // ──────────────────────────────────────────
    {
      date: '2026-02-07',
      items: [
        {
          id: 's2-1',
          type: 'activity',
          title: '기상 및 준비',
          time: '07:00',
          duration: 60,
          location: { name: '사라사호텔 신사이바시', lat: 34.6742, lng: 135.5002 },
        },
        {
          id: 's2-2',
          type: 'transport',
          title: '호텔 → 후시미이나리역 이동',
          time: '08:00',
          duration: 53,
          location: { name: '나가호리바시역', lat: 34.6740, lng: 135.5060 },
          notes: '나가호리바시역 → 기타하마역 → 단바바시역 → 후시미이나리역',
          price: 670,
          currency: 'JPY',
        },
        {
          id: 's2-3',
          type: 'attraction',
          title: '후시미 이나리 신사 — 토리이 산책',
          time: '09:00',
          duration: 120,
          location: { name: '후시미 이나리 신사', lat: 34.9671, lng: 135.7727 },
        },
        {
          id: 's2-4',
          type: 'restaurant',
          title: '점심 — 와규 연어 라멘',
          time: '11:00',
          duration: 60,
          location: { name: '살몬 누들 교토', lat: 34.9640, lng: 135.7720 },
          price: 3000,
          currency: 'JPY',
        },
        {
          id: 's2-5',
          type: 'restaurant',
          title: '산도 차야 — 프라페',
          time: '12:00',
          duration: 60,
          location: { name: '산도 차야', lat: 34.9640, lng: 135.7730 },
        },
        {
          id: 's2-6',
          type: 'transport',
          title: '후시미이나리역 → 기요미즈고조역 이동',
          time: '13:00',
          duration: 30,
          location: { name: '후시미이나리역', lat: 34.9663, lng: 135.7720 },
          notes: 'JR선 보통 → 기요미즈고조역 → 도보 19분',
          price: 240,
          currency: 'JPY',
        },
        {
          id: 's2-7',
          type: 'attraction',
          title: '산넨자카 · 니넨자카 산책',
          time: '13:30',
          duration: 90,
          location: { name: '산넨자카', lat: 34.9977, lng: 135.7808 },
        },
        {
          id: 's2-8',
          type: 'transport',
          title: '산넨자카 → 니시키 시장 이동 (도보)',
          time: '15:00',
          duration: 30,
          location: { name: '산넨자카', lat: 34.9977, lng: 135.7808 },
        },
        {
          id: 's2-9',
          type: 'attraction',
          title: '니시키 시장 구경',
          time: '15:30',
          duration: 60,
          location: { name: '니시키 시장', lat: 35.0050, lng: 135.7655 },
        },
        {
          id: 's2-10',
          type: 'attraction',
          title: '야사카 신사 노을 구경',
          time: '17:00',
          duration: 60,
          location: { name: '야사카 신사', lat: 35.0037, lng: 135.7785 },
        },
        {
          id: 's2-11',
          type: 'attraction',
          title: '시라카와 운하 · 시조-산조 산책',
          time: '18:00',
          duration: 60,
          location: { name: '시라카와 운하', lat: 35.0062, lng: 135.7745 },
        },
        {
          id: 's2-12',
          type: 'attraction',
          title: '폰토초 거리 구경',
          time: '19:00',
          duration: 30,
          location: { name: '폰토초', lat: 35.0057, lng: 135.7727 },
        },
        {
          id: 's2-13',
          type: 'restaurant',
          title: '저녁 — 야키니쿠',
          time: '19:30',
          duration: 60,
          location: { name: '야키니쿠 이자카야 774', lat: 35.0056, lng: 135.7726 },
          price: 3500,
          currency: 'JPY',
        },
        {
          id: 's2-14',
          type: 'transport',
          title: '교토 → 호텔 이동',
          time: '20:30',
          duration: 52,
          location: { name: '교토카와라마치역', lat: 35.0031, lng: 135.7713 },
          notes: '한큐 교토선 → 아와지역 → 사카이스지선 → 나가호리바시역 → 도보',
          price: 650,
          currency: 'JPY',
        },
      ],
    },
    // ──────────────────────────────────────────
    // Day 3 · 2026-02-08 · 야마자키 & 산토리
    // ──────────────────────────────────────────
    {
      date: '2026-02-08',
      items: [
        {
          id: 's3-1',
          type: 'activity',
          title: '기상 및 준비',
          time: '07:00',
          duration: 60,
          location: { name: '사라사호텔 신사이바시', lat: 34.6742, lng: 135.5002 },
        },
        {
          id: 's3-2',
          type: 'attraction',
          title: '글리코상 · 도톤보리 아침 산책',
          time: '08:00',
          duration: 60,
          location: { name: '글리코상 (도톤보리)', lat: 34.6688, lng: 135.5013 },
        },
        {
          id: 's3-3',
          type: 'restaurant',
          title: '아침 — 쵸우쵸우 (토스트 & 커피)',
          time: '09:00',
          duration: 30,
          location: { name: '쵸우쵸우', lat: 34.6680, lng: 135.5065 },
          price: 1000,
          currency: 'JPY',
        },
        {
          id: 's3-4',
          type: 'transport',
          title: '호텔 → 야마자키 증류소 이동',
          time: '09:30',
          duration: 66,
          location: { name: '닛폰바시역', lat: 34.6645, lng: 135.5065 },
          notes: '닛폰바시역 → 아와지역 → 오야마자키역 → 도보 10분',
          price: 570,
          currency: 'JPY',
        },
        {
          id: 's3-5',
          type: 'activity',
          title: '야마자키 증류소 투어',
          time: '11:00',
          duration: 60,
          location: { name: '야마자키 증류소', lat: 34.8954, lng: 135.6679 },
        },
        {
          id: 's3-6',
          type: 'restaurant',
          title: '점심 식사',
          time: '12:00',
          duration: 60,
          location: { name: '오야마자키', lat: 34.8900, lng: 135.6700 },
          notes: '오코노미야키 야마키 또는 かぎ卯',
          price: 1500,
          currency: 'JPY',
        },
        {
          id: 's3-7',
          type: 'transport',
          title: '야마자키 → 산토리 맥주공장 이동',
          time: '13:00',
          duration: 23,
          location: { name: '오야마자키역', lat: 34.8900, lng: 135.6680 },
          notes: '오야마자키역 → 니시야마텐노잔역 → 도보 11분',
          price: 170,
          currency: 'JPY',
        },
        {
          id: 's3-8',
          type: 'activity',
          title: '산토리 맥주공장 투어',
          time: '13:50',
          duration: 90,
          location: { name: '산토리 교토 맥주공장', lat: 34.8844, lng: 135.6724 },
        },
        {
          id: 's3-9',
          type: 'transport',
          title: '산토리 → 난바 파크스 이동',
          time: '15:20',
          duration: 67,
          location: { name: '니시야마텐노잔역', lat: 34.8832, lng: 135.6710 },
          notes: '한큐 교토선 → 사카이스지선 → 에비스초역 → 도보 10분',
          price: 570,
          currency: 'JPY',
        },
        {
          id: 's3-10',
          type: 'attraction',
          title: '난바 파크스 구경',
          time: '17:00',
          duration: 30,
          location: { name: '난바 파크스', lat: 34.6594, lng: 135.5009 },
        },
        {
          id: 's3-11',
          type: 'restaurant',
          title: '저녁 — 스시',
          time: '17:30',
          duration: 90,
          location: { name: '카미나리 스시', lat: 34.6640, lng: 135.5020 },
          notes: '단품 스시',
          price: 4000,
          currency: 'JPY',
        },
        {
          id: 's3-12',
          type: 'restaurant',
          title: '야식 — 이자카야',
          time: '19:00',
          duration: 60,
          location: { name: '난바', lat: 34.6631, lng: 135.5018 },
          notes: '토리키조쿠 또는 쿠시카츠 아게텐캇',
          price: 2500,
          currency: 'JPY',
        },
      ],
    },
    // ──────────────────────────────────────────
    // Day 4 · 2026-02-09 · 귀국
    // ──────────────────────────────────────────
    {
      date: '2026-02-09',
      items: [
        {
          id: 's4-1',
          type: 'activity',
          title: '기상 및 짐 정리',
          time: '07:00',
          duration: 60,
          location: { name: '사라사호텔 신사이바시', lat: 34.6742, lng: 135.5002 },
        },
        {
          id: 's4-2',
          type: 'hotel',
          title: '호텔 체크아웃',
          time: '08:00',
          duration: 15,
          location: { name: '사라사호텔 신사이바시', lat: 34.6742, lng: 135.5002 },
          notes: '체크아웃 10:00 전',
        },
        {
          id: 's4-3',
          type: 'transport',
          title: '호텔 → 간사이공항 이동',
          time: '08:15',
          duration: 49,
          location: { name: '나가호리바시역', lat: 34.6740, lng: 135.5060 },
          notes: '나가호리바시역 → 덴가차야역 → 난카이 공항선 → 간사이공항역',
          price: 1210,
          currency: 'JPY',
        },
        {
          id: 's4-4',
          type: 'transport',
          title: '간사이 → 인천 (ZE612)',
          time: '11:50',
          duration: 120,
          location: { name: '간사이국제공항', lat: 34.4272, lng: 135.2440 },
          notes: '이스타항공 ZE612 · 예약번호 U53W5C · 도착 13:50',
        },
      ],
    },
  ],
}
